import "dotenv/config";

export interface Environment {
  SERVER_PORT: number;
  OPENAI_ORGANIZATION: string;
  OPENAI_PROJECT: string;
  OPENAI_API_KEY: string;
  OPENAI_ASSISTANT_ID_OPERATOR: string;
  OPENAI_ASSISTANT_ID_ORDINANCES: string;
}
export const ENV = {
  SERVER_PORT: process.env.SERVER_PORT || 8000,
  OPENAI_ORGANIZATION: process.env.OPENAI_ORGANIZATION,
  OPENAI_PROJECT: process.env.OPENAI_PROJECT,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_ASSISTANT_ID_OPERATOR: process.env.OPENAI_ASSISTANT_ID_OPERATOR,
  OPENAI_ASSISTANT_ID_ORDINANCES: process.env.OPENAI_ASSISTANT_ID_ORDINANCES,
} as Environment;
